name: Release DEB package

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-deb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-stdeb fakeroot dpkg-dev

      - name: Build source distribution
        run: python3 setup.py sdist

      - name: Build DEB package
        run: |
          python3 setup.py --command-packages=stdeb.command bdist_deb

      - name: Upload DEB artifact
        uses: actions/upload-artifact@v4
        with:
          name: ai-bash-deb
          path: deb_dist/*.deb
